-- MySQL Script generated by MySQL Workbench
-- 02/08/16 11:47:17
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tesseract
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tesseract
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tesseract` DEFAULT CHARACTER SET utf8 ;
USE `tesseract` ;

-- -----------------------------------------------------
-- Table `tesseract`.`organisation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tesseract`.`organisation` (
  `id_organisation` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `adress` VARCHAR(45) NULL,
  `matricule` VARCHAR(45) NULL,
  `photo` VARCHAR(45) NULL,
  PRIMARY KEY (`id_organisation`),
  UNIQUE INDEX `matricule_UNIQUE` (`matricule` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tesseract`.`utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tesseract`.`utilisateur` (
  `id_utilisateur` INT NOT NULL AUTO_INCREMENT,
  `id_organisation` INT NULL,
  `nom_utilisateur` VARCHAR(45) NULL,
  `mot_de_passe` VARCHAR(45) NULL,
  `nom` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NULL,
  `date_naissance` DATE NULL,
  `tel` INT NULL,
  `adresse` VARCHAR(45) NULL,
  `mail` VARCHAR(45) NULL,
  `photo` INT NULL,
  `role` VARCHAR(3) NULL,
  `score` INT NULL,
  `cv` VARCHAR(45) NULL,
  `etat` VARCHAR(3) NULL,
  `mail_sercours` VARCHAR(45) NULL,
  PRIMARY KEY (`id_utilisateur`),
  INDEX `fk_users_organisations1_idx` (`id_organisation` ASC),
  UNIQUE INDEX `nom_utilisateur_UNIQUE` (`nom_utilisateur` ASC),
  CONSTRAINT `fk_users_organisations1`
    FOREIGN KEY (`id_organisation`)
    REFERENCES `tesseract`.`organisation` (`id_organisation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tesseract`.`reclamation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tesseract`.`reclamation` (
  `id_reclamation` INT NOT NULL AUTO_INCREMENT,
  `id_utilisateur` INT NULL,
  `sujet` VARCHAR(200) NULL,
  `description` TEXT(100) NULL,
  `etat` VARCHAR(3) NULL,
  `date_reclamation` VARCHAR(45) NULL,
  PRIMARY KEY (`id_reclamation`),
  INDEX `fk_reclamation_utilisateur1_idx` (`id_utilisateur` ASC),
  CONSTRAINT `fk_reclamation_utilisateur1`
    FOREIGN KEY (`id_utilisateur`)
    REFERENCES `tesseract`.`utilisateur` (`id_utilisateur`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tesseract`.`matiere`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tesseract`.`matiere` (
  `id_matiere` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`id_matiere`),
  UNIQUE INDEX `nom_UNIQUE` (`nom` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tesseract`.`cours`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tesseract`.`cours` (
  `id_cours` INT NOT NULL AUTO_INCREMENT,
  `id_matiere` INT NULL,
  `nom` VARCHAR(45) NULL,
  `difficulte` VARCHAR(45) NULL,
  `description` VARCHAR(100) NULL,
  `badge` VARCHAR(45) NULL,
  `affiche` VARCHAR(45) NULL,
  PRIMARY KEY (`id_cours`),
  INDEX `fk_cours_matiere1_idx` (`id_matiere` ASC),
  CONSTRAINT `fk_cours_matiere1`
    FOREIGN KEY (`id_matiere`)
    REFERENCES `tesseract`.`matiere` (`id_matiere`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tesseract`.`chapitre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tesseract`.`chapitre` (
  `id_chapitre` INT NOT NULL AUTO_INCREMENT,
  `id_cours` INT NULL,
  `nom` VARCHAR(45) NULL,
  `numero` INT NULL,
  `description` VARCHAR(45) NULL,
  `resume` VARCHAR(45) NULL,
  PRIMARY KEY (`id_chapitre`),
  INDEX `fk_chapitre_cours1_idx` (`id_cours` ASC),
  CONSTRAINT `fk_chapitre_cours1`
    FOREIGN KEY (`id_cours`)
    REFERENCES `tesseract`.`cours` (`id_cours`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tesseract`.`objectif`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tesseract`.`objectif` (
  `id_objectif` INT NOT NULL AUTO_INCREMENT,
  `id_chapitre` INT NULL,
  `nom` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `difficule` VARCHAR(3) NULL,
  PRIMARY KEY (`id_objectif`),
  INDEX `fk_objectif_chapitre1_idx` (`id_chapitre` ASC),
  CONSTRAINT `fk_objectif_chapitre1`
    FOREIGN KEY (`id_chapitre`)
    REFERENCES `tesseract`.`chapitre` (`id_chapitre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tesseract`.`epreuve`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tesseract`.`epreuve` (
  `id_epreuve` INT NOT NULL AUTO_INCREMENT,
  `id_cours` INT NULL,
  `id_objectif` INT NULL,
  `type` VARCHAR(3) NULL,
  `difficulte` VARCHAR(45) NULL,
  `duree` INT NULL,
  PRIMARY KEY (`id_epreuve`),
  INDEX `fk_epreuve_cours1_idx` (`id_cours` ASC),
  INDEX `fk_epreuve_objectif1_idx` (`id_objectif` ASC),
  CONSTRAINT `fk_epreuve_cours1`
    FOREIGN KEY (`id_cours`)
    REFERENCES `tesseract`.`cours` (`id_cours`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_epreuve_objectif1`
    FOREIGN KEY (`id_objectif`)
    REFERENCES `tesseract`.`objectif` (`id_objectif`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tesseract`.`question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tesseract`.`question` (
  `id_question` INT NOT NULL AUTO_INCREMENT,
  `id_epreuve` INT NULL,
  `question` VARCHAR(200) NULL,
  PRIMARY KEY (`id_question`),
  INDEX `fk_question_epreuve1_idx` (`id_epreuve` ASC),
  CONSTRAINT `fk_question_epreuve1`
    FOREIGN KEY (`id_epreuve`)
    REFERENCES `tesseract`.`epreuve` (`id_epreuve`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tesseract`.`reponse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tesseract`.`reponse` (
  `id_reponse` INT NOT NULL AUTO_INCREMENT,
  `id_question` INT NULL,
  `reponse` VARCHAR(45) NULL,
  `justification` VARCHAR(45) NULL,
  `etat` INT NULL,
  PRIMARY KEY (`id_reponse`),
  INDEX `fk_reponse_question1_idx` (`id_question` ASC),
  CONSTRAINT `fk_reponse_question1`
    FOREIGN KEY (`id_question`)
    REFERENCES `tesseract`.`question` (`id_question`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tesseract`.`commentaire_cours`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tesseract`.`commentaire_cours` (
  `id_commentaire` INT NOT NULL,
  `id_cours` INT NULL,
  `commentaire` VARCHAR(400) NULL,
  `date_commentaire` DATE NULL,
  PRIMARY KEY (`id_commentaire`),
  INDEX `fk_commentaire_cours_cours1_idx` (`id_cours` ASC),
  CONSTRAINT `fk_commentaire_cours_cours1`
    FOREIGN KEY (`id_cours`)
    REFERENCES `tesseract`.`cours` (`id_cours`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tesseract`.`invitation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tesseract`.`invitation` (
  `id_utilisateur` INT NOT NULL,
  `id_organisation` INT NOT NULL,
  `sens` VARCHAR(2) NULL,
  `etat` VARCHAR(3) NULL,
  `date_invitation` DATE NULL,
  PRIMARY KEY (`id_utilisateur`, `id_organisation`),
  INDEX `fk_utilisateur_has_organisation_organisation1_idx` (`id_organisation` ASC),
  INDEX `fk_utilisateur_has_organisation_utilisateur1_idx` (`id_utilisateur` ASC),
  CONSTRAINT `fk_utilisateur_has_organisation_utilisateur1`
    FOREIGN KEY (`id_utilisateur`)
    REFERENCES `tesseract`.`utilisateur` (`id_utilisateur`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_utilisateur_has_organisation_organisation1`
    FOREIGN KEY (`id_organisation`)
    REFERENCES `tesseract`.`organisation` (`id_organisation`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tesseract`.`log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tesseract`.`log` (
  `id_log` INT NOT NULL AUTO_INCREMENT,
  `id_utilisateur` INT NULL,
  `tache` VARCHAR(45) NULL,
  `date_tache` DATETIME NULL,
  PRIMARY KEY (`id_log`),
  INDEX `fk_log_utilisateur1_idx` (`id_utilisateur` ASC),
  CONSTRAINT `fk_log_utilisateur1`
    FOREIGN KEY (`id_utilisateur`)
    REFERENCES `tesseract`.`utilisateur` (`id_utilisateur`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tesseract`.`notification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tesseract`.`notification` (
  `id_notification` INT NOT NULL AUTO_INCREMENT,
  `id_utilisateur` INT NULL,
  `notification` VARCHAR(100) NULL,
  `date_notification` DATETIME NULL,
  PRIMARY KEY (`id_notification`),
  INDEX `fk_notification_utilisateur1_idx` (`id_utilisateur` ASC),
  CONSTRAINT `fk_notification_utilisateur1`
    FOREIGN KEY (`id_utilisateur`)
    REFERENCES `tesseract`.`utilisateur` (`id_utilisateur`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tesseract`.`session_cours`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tesseract`.`session_cours` (
  `id_utilisateur` INT NOT NULL,
  `id_cours` INT NOT NULL,
  `date_session` DATE NULL,
  PRIMARY KEY (`id_utilisateur`, `id_cours`),
  INDEX `fk_utilisateur_has_cours_cours1_idx` (`id_cours` ASC),
  INDEX `fk_utilisateur_has_cours_utilisateur1_idx` (`id_utilisateur` ASC),
  CONSTRAINT `fk_utilisateur_has_cours_utilisateur1`
    FOREIGN KEY (`id_utilisateur`)
    REFERENCES `tesseract`.`utilisateur` (`id_utilisateur`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_utilisateur_has_cours_cours1`
    FOREIGN KEY (`id_cours`)
    REFERENCES `tesseract`.`cours` (`id_cours`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tesseract`.`session_epreuve`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tesseract`.`session_epreuve` (
  `id_utilisateur` INT NOT NULL,
  `id_epreuve` INT NOT NULL,
  `note` FLOAT NULL,
  `nbr_tentative` INT NULL,
  `date_session` DATE NULL,
  PRIMARY KEY (`id_utilisateur`, `id_epreuve`),
  INDEX `fk_utilisateur_has_epreuve_epreuve1_idx` (`id_epreuve` ASC),
  INDEX `fk_utilisateur_has_epreuve_utilisateur1_idx` (`id_utilisateur` ASC),
  CONSTRAINT `fk_utilisateur_has_epreuve_utilisateur1`
    FOREIGN KEY (`id_utilisateur`)
    REFERENCES `tesseract`.`utilisateur` (`id_utilisateur`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_utilisateur_has_epreuve_epreuve1`
    FOREIGN KEY (`id_epreuve`)
    REFERENCES `tesseract`.`epreuve` (`id_epreuve`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tesseract`.`sujet_forum`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tesseract`.`sujet_forum` (
  `id_sujet` INT NOT NULL AUTO_INCREMENT,
  `id_utilisateur` INT NULL,
  `titre` VARCHAR(45) NULL,
  `description` TEXT NULL,
  `date_sujet` DATETIME NULL,
  PRIMARY KEY (`id_sujet`),
  INDEX `fk_sujet_forum_utilisateur1_idx` (`id_utilisateur` ASC),
  CONSTRAINT `fk_sujet_forum_utilisateur1`
    FOREIGN KEY (`id_utilisateur`)
    REFERENCES `tesseract`.`utilisateur` (`id_utilisateur`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tesseract`.`commentraire_forum`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tesseract`.`commentraire_forum` (
  `id_utilisateur` INT NOT NULL,
  `id_sujet` INT NOT NULL,
  `contenu` TEXT NULL,
  `date_commentraire` DATETIME NULL,
  PRIMARY KEY (`id_utilisateur`, `id_sujet`),
  INDEX `fk_utilisateur_has_sujet_forum_sujet_forum1_idx` (`id_sujet` ASC),
  INDEX `fk_utilisateur_has_sujet_forum_utilisateur1_idx` (`id_utilisateur` ASC),
  CONSTRAINT `fk_utilisateur_has_sujet_forum_utilisateur1`
    FOREIGN KEY (`id_utilisateur`)
    REFERENCES `tesseract`.`utilisateur` (`id_utilisateur`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_utilisateur_has_sujet_forum_sujet_forum1`
    FOREIGN KEY (`id_sujet`)
    REFERENCES `tesseract`.`sujet_forum` (`id_sujet`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tesseract`.`ban_forum`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tesseract`.`ban_forum` (
  `id_ban` INT NOT NULL AUTO_INCREMENT,
  `id_utilisateur` INT NULL,
  `cause` VARCHAR(45) NULL,
  `date_ban` DATE NULL,
  `duree` INT NULL,
  PRIMARY KEY (`id_ban`),
  INDEX `fk_ban_forum_utilisateur1_idx` (`id_utilisateur` ASC),
  CONSTRAINT `fk_ban_forum_utilisateur1`
    FOREIGN KEY (`id_utilisateur`)
    REFERENCES `tesseract`.`utilisateur` (`id_utilisateur`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tesseract`.`evenement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tesseract`.`evenement` (
  `id_evenement` INT NOT NULL AUTO_INCREMENT,
  `id_organisation` INT NULL,
  `nom` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `nbr_max` VARCHAR(45) NULL,
  `affiche` VARCHAR(45) NULL,
  `date_evenement` DATETIME NULL,
  PRIMARY KEY (`id_evenement`),
  INDEX `fk_evenement_organisation1_idx` (`id_organisation` ASC),
  CONSTRAINT `fk_evenement_organisation1`
    FOREIGN KEY (`id_organisation`)
    REFERENCES `tesseract`.`organisation` (`id_organisation`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tesseract`.`inscription_evenement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tesseract`.`inscription_evenement` (
  `id_evenement` INT NOT NULL,
  `id_utilisateur` INT NOT NULL,
  `date_inscription` DATE NULL,
  PRIMARY KEY (`id_evenement`, `id_utilisateur`),
  INDEX `fk_evenement_has_utilisateur_utilisateur1_idx` (`id_utilisateur` ASC),
  INDEX `fk_evenement_has_utilisateur_evenement1_idx` (`id_evenement` ASC),
  CONSTRAINT `fk_evenement_has_utilisateur_evenement1`
    FOREIGN KEY (`id_evenement`)
    REFERENCES `tesseract`.`evenement` (`id_evenement`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_evenement_has_utilisateur_utilisateur1`
    FOREIGN KEY (`id_utilisateur`)
    REFERENCES `tesseract`.`utilisateur` (`id_utilisateur`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tesseract`.`challenge`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tesseract`.`challenge` (
  `id_challenge` INT NOT NULL AUTO_INCREMENT,
  `id_organisation` INT NULL,
  `nom` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `theme` VARCHAR(45) NULL,
  `date_challenge` DATETIME NULL,
  PRIMARY KEY (`id_challenge`),
  INDEX `fk_challenge_organisation1_idx` (`id_organisation` ASC),
  CONSTRAINT `fk_challenge_organisation1`
    FOREIGN KEY (`id_organisation`)
    REFERENCES `tesseract`.`organisation` (`id_organisation`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tesseract`.`inscription_challenge`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tesseract`.`inscription_challenge` (
  `id_utilisateur` INT NOT NULL,
  `id_organisation` INT NOT NULL,
  `date_inscription` DATE NULL,
  `inscription_challengecol` VARCHAR(45) NULL,
  PRIMARY KEY (`id_utilisateur`, `id_organisation`),
  INDEX `fk_utilisateur_has_organisation_organisation2_idx` (`id_organisation` ASC),
  INDEX `fk_utilisateur_has_organisation_utilisateur2_idx` (`id_utilisateur` ASC),
  CONSTRAINT `fk_utilisateur_has_organisation_utilisateur2`
    FOREIGN KEY (`id_utilisateur`)
    REFERENCES `tesseract`.`utilisateur` (`id_utilisateur`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_utilisateur_has_organisation_organisation2`
    FOREIGN KEY (`id_organisation`)
    REFERENCES `tesseract`.`organisation` (`id_organisation`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
